### PR TITLE
Fix some memory leaks

### LINKED ISSUE #120: Memory increase when using shapeWithTrace
The `shapeWithTrace` method uses a locally scoped function `traceFunc` that is added to the WASM interface on each call.

This is not a memory leak, but the function is registered every time the call is made, and the `wasmExports.__indirect_function_table` grows for each call to `shapeWithTrace`. It can quickly consume megabytes of RAM.

**Emscripten Solution**
Emscripten exposes an `addFunction` method in the `hb.js` file. Oddly, this uses a function `getEmptySlot` that appears to check first in `freeTableIndexes` - but this table is never populated.

It appears that there should be a corresponding `removeFunction`, something like this:

```js
      var removeFunction = (func) => {
        var idx = getFunctionAddress(func);
        if (idx) {
          wasmTable.set(idx, null);
          freeTableIndexes.push(idx);
        }
      };
```

and then `removeFunction(traceFunc)` called after shaping, just before the `traceFunc` goes out of scope.

This works, but I'm unhappy having to mess with the emscripten generated hb.js file.

**Alternative solution**
For the time being, I've shuffled around `hbjs.js` to only call the `addFunction` once (in a similar manner to the `drawFuncsPtr` of `hbjs.js`).

The `traceFunc` I moved outside of the `shapeWithTrace` method, and used a `shapeWithTraceFuncPtr` variable to register only once.
However, the closure variables can no longer be accessed, and it involved creating an object wide `var temp = [ ];` that is used to pass in the required parameters into the function that has lost the closure scope.

Hacky, but it's not consuming lots of array space now!

_Any better solutions would be most welcome!_

### PR DESCRIPTION
**Pull request by khaledhosny**
Fixes #120

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -2,197 +2,196 @@ const fs = require('fs');
...
-  if (this.blob) this.blob.destroy();
-  if (this.face) this.face.destroy();
-  if (this.font) this.font.destroy();
-  if (this.buffer) this.buffer.destroy();
-  this.blob = this.face = this.font = this.buffer = null;
+  if (blob) blob.destroy();
+  if (face) face.destroy();
+  if (font) font.destroy();
+  if (buffer) buffer.destroy();
+  blob = face = font = buffer = undefined;
```
Comment (chearon) [inline test/index.js:16]: Oh whoops. Apparently shared context via `this` only works if the `afterEach` is defined in a `describe`. I think I like this fix since it's compatible with the new-ish `node:test`.

**Review by chearon — APPROVED** [review]
